class FxId:
    # DRIVE start
    DRIVE_START_DUST_CURRENT = 10
    DRIVE_START_SMOKE_PSLIB = 11
    DRIVE_START_SMOKE_VAND_DUST = 12

    # DRIVE hit
    DRIVE_HIT_SPARKS_CURRENT = 20
    DRIVE_HIT_EXPLOSION_PSLIB = 21
    DRIVE_HIT_EXPLOSION_PSLIB_PLUS_SPARKS = 22
    DRIVE_HIT_VAND_EXPLOSION = 23
    DRIVE_HIT_VAND_EXPLOSION_PLUS_SPARKS = 24
